export const INIT_BLOG_LIST_SUCCESS = 'INIT_BLOG_LIST_SUCCESS';
export const INIT_BLOG_LIST_FAIL = 'INIT_BLOG_LIST_FAIL';
export const SHOW_BLOG_CONTENT = 'SHOW_BLOG_CONTENT';
export const ADD_BLOG = 'ADD_BLOG';
export const DELETE_BLOG = 'DELETE_BLOG';